import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MenuBar from "./_component/MenuBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next_API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="bg-linear-to-r from-cyan-500 to-blue-500 py-4 text-center">
            <h1>Next API</h1>
            <div className="flex justify-center space-x-5">
               <MenuBar/>
            </div>
           
          </header>
        {children}

        <footer className="bg-linear-to-r from-cyan-500 to-blue-500 p-2 fixed bottom-0 w-full text-center">
           <p> &copy; developed by RAHUL Yadav 2025</p>
        </footer>
      </body>
    </html>
  );
}
